### ISSUE TITLE
Long Polling on getRendererState request is not reliable

### ISSUE THREAD

**Issue by ChriD** [ChriD/Raumserver#55]
The Long Polling on getRendererState request is not reliable.
If there are many states chageing in a row, then it may be that they will not be catched

**Comment by ChriD** [comment]
In fact the problem is the generation of the uniqueId for the long polling which will be the sme if called fast. So i have to jump in here!

**Comment by ChriD** [comment]
I've updated the random number genarator to a random unqiue unit generator. This will do its job

**Comment by vicegold** [comment]
👍

**Comment by mtenkoppel** [comment]
Hi Chris, how exactly do I build the binaries? I tried running build.sh and it created some folders but without binaries. Thanks!

**Comment by ChriD** [comment]
install the approriate compiler (g++5) and then use the build script for what architecture you want to build
e.g buildX64.sh for linuxX64
build.sh would need some parameters which will be provoded by e.g buildX64.sh

BTW: you have to build the RaumkernelLib (https://github.com/ChriD/RaumkernelLib), the RaumserverLib https://github.com/ChriD/RaumserverLib) and the Deamon one by one beginning with the kernel 

If there is any error it will be shown in the console.

**Comment by mtenkoppel** [comment]
Hi again!
The issue I am observing with Raumkernellib/Raumserverlib 1.0 is that after a while making a request to "raumserver/data/getRendererState" results in not responding and then crashing the daemon. 

Interesting enough, restarting the daemon and calling /getRendererState results immediately in a crash. I am running Raumserver on a Pi and only rebooting the PI or the Raumfeld host resolves the situation. I cannot really explain this...

I this what you fixed with your change? Unfortuately I am not able to compile so there I cannot test it. Would there anyway you could provide binaries for ARMv7 to me? 

cheers!

**Comment by ChriD** [comment]
I do not know if this issue is fixed in the current repo.
To find such problems i have added a stacktrace to the log but it does not work for ARM's as far as i tested

So, i can build you the current repo for ARMV7 and you may test this version. If it crashes please have a look in the log file if there is any stacktrace or if its the same as on the RF-ARM devices.

I'll let you know when i built it.

**Comment by ChriD** [comment]
Sorry, i have a lot of work to do so i didnt build it yet! I have not forgotten you!
